# Generated by Django 5.1.1 on 2025-05-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre_ids',
            field=models.JSONField(default=list),
        ),
    ]
